-- 코드를 입력하세요
SELECT A.PRODUCT_ID,	A.PRODUCT_NAME ,  SUM(B.AMOUNT)*MAX(A.PRICE) TOTAL_SALES
from FOOD_PRODUCT A
join food_order B
on A.PRODUCT_ID = B.PRODUCT_ID
where to_char(B.PRODUCE_DATE,'YYYY-MM-DD') like '2022-05%'
group by A.PRODUCT_ID,	A.PRODUCT_NAME
order by TOTAL_SALES desc, A.PRODUCT_ID